---
openapi: 3.0.1
info:
  title: Crypto Price Track
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Users
  - name: alerts
paths:
  /users/sign_in:
    post:
      tags:
        - Users
      summary: Sign In
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user:
                  email: test@test.com
                  password: test@test.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/:
    post:
      tags:
        - Users
      summary: Signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                user:
                  email: test@test.com
                  password: test@test.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /users/sign_out:
    delete:
      tags:
        - Users
      summary: Log Out
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /alerts/create:
    post:
      tags:
        - alerts
      summary: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                alert:
                  target_price: '22100'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /alerts/delete:
    post:
      tags:
        - alerts
      summary: delete
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                alert:
                  target_price: '22100'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /alerts/all_alerts:
    get:
      tags:
        - alerts
      summary: Fetch All Alerts with params
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: status
          in: query
          schema:
            type: string
          example: deleted
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /:
    get:
      tags:
        - default
      summary: New Request
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
servers:
- url: http://{localHost}
  variables:
    defaultHost:
      default: www.example.com
    localHost:
      default: localhost:3000
